spring:
  application:
    name: AILearn

  datasource:
    url: jdbc:mysql://ai-learn-mysql.czjvlvg6odpf.ap-northeast-2.rds.amazonaws.com:3306/ai_learn
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    session:
      timeout: 30m
  port: 8080

alanai:
  api:
    question_url: https://kdt-api-function.azurewebsites.net/api/v1/question
    sse_streaming_url: https://kdt-api-function.azurewebsites.net/api/v1/sse-streaming
    key: ${ALANAI_API_KEY}