spring:
  application:
    name: AILearn

  datasource:
    url: jdbc:mysql://ai-learn-mysql.czjvlvg6odpf.ap-northeast-2.rds.amazonaws.com:3306/ai_learn
    username: admin
    password: adminpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "duudu0704@gmail.com"
    password: "pehm qcgn owbv muix"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    session:
      timeout: 30m
  port: 8080

alanai:
  api:
    question_url: https://kdt-api-function.azurewebsites.net/api/v1/question
    sse_streaming_url: https://kdt-api-function.azurewebsites.net/api/v1/sse-streaming
    key: 5f7e6b7f-dcee-4151-b97e-9063effd27c5