name: path-filter
on:
  push:
    paths:
      - '.github/workflows/temp/*'
      - '!.github/workflows/temp/push.yaml'

jobs:
  path-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo hello