name: EC2 Docker Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. SSH로 EC2에 연결하여 배포 작업 수행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/AILearn  # 애플리케이션이 위치한 경로로 이동
            
            # 최신 코드 pull
            git pull origin develop
            
            # 도커 컴포즈를 사용하여 컨테이너 재시작
            docker-compose down  # 기존 도커 컨테이너 중지
            docker-compose up -d  # 도커 컨테이너 다시 시작
